# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('location', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.Packages'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
