# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_auto_20181219_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='height_field',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='width_field',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
